Add IPython support
adder46/pyhstr pull request #1
Opened 2020-09-15 03:20 UTC by mcataford

## Description

These changes allow the application to work within IPython as it does in the classic Python shell. It leverages IPython's [custom magic](https://ipython.readthedocs.io/en/stable/config/custommagics.html) instead of passing by the display hook -- this results in a much simpler integration as toying with `sys.displayhook` in IPython is a bit thorny.

Using line magic, the history application can be called via `%ihh` and results in the same interactivity as using `hh` in the regular shell. Since custom magics are registered on import, a check to see if `IPython` exists as an importable package gates it; this way, we avoid wonky behaviour when `IPython` is not available.

## QA

- Spun up a venv, packaged and installed `pyhstr` but not `IPython`.
- Tried out the regular command (i..e `python -ic "from pyhstr import hh"`) and verified that `hh` works as expected in the shell.
- Spun up another venv, this time with `pyhstr` and `IPython`.
- Started `IPython` via `ipython -i -c="from pyhstr import ihh"`.
- Called `%ihh` from within the `IPython` shell.
- Verified that behaviour is similar to what happens in the regular shell.

2020-09-15 15:13 UTC, Akuli requested changes

2020-09-15 15:13 UTC, Akuli commented on pyhstr/__init__.py
> +        from pyhstr.ipyhstr import ihh
Why do you need to check for existence of `IPython` instead of just importing `pyhstr` and handling the error?

2020-09-15 15:13 UTC, Akuli commented on pyhstr/__init__.py
> +except:
This should probably be `except ImportError` or similar. Plain `except` also catches `KeyboardInterrupt` and other exceptions that we don't want to suppress here.

2020-09-15 15:13 UTC, Akuli commented on README.md
> +![screenshot](pyhstr.gif)
I think the screenshot should be before `#### With IPython`. @adder46 what do you think?

2020-09-15 15:22 UTC, Akuli commented
Is the IPython command be named `%ihh` or `%hh`? The docstring of `ihh()` says `%hh`, but everything else seems to say `%ihh`.

2020-09-15 17:23 UTC, mcataford commented on pyhstr/__init__.py
> +        from pyhstr.ipyhstr import ihh
That would be fine too, I'll amend this to import and catch the `ImportError` that might crop up.

2020-09-15 17:23 UTC, mcataford commented on pyhstr/__init__.py
> +except:
Good call, related to the comment above. Will push up a fix shortly.

2020-09-15 17:25 UTC, mcataford commented
The command is `%ihh`, the docstring was overlooked. Will fix shortly.

2020-09-16 12:44 UTC, mcataford commented on pyhstr/__init__.py
> +        from pyhstr.ipyhstr import ihh
Addressed.

2020-09-16 12:44 UTC, mcataford commented on pyhstr/__init__.py
> +except:
Addressed.

2020-09-16 12:46 UTC, mcataford commented on README.md
> +![screenshot](pyhstr.gif)
If you have a suggestion for a decent GIF capture tool that's Debian-friendly, I can generate a similar GIF for the IPython use case, too.

2020-09-16 12:46 UTC, mcataford commented
Addressed review comments & re-ran through QA.

2020-09-19 16:58 UTC, Akuli commented
Should it be named `%ihh` or `%hh`? IMO the fact that you're using `IPython` shouldn't mean that you need to type `i` in front of every command.

Also, does pyhstr find the history of commands typed into ipython?

2020-09-19 17:08 UTC, adder46 commented
It just looks at `"~/.python_history"` for the regular Python shell. I guess that's not where IPython stores the history. So this should be addressed, too.

2020-09-20 00:45 UTC, adder46 commented
I was just thinking, so the app would need to detect whether the user is using an ordinary Python shell, or IPython, and load appropriate history file accordingly. I was googling a bit for ways to do it, and unfortunately I haven't found a neat way to do it. I also looked in `sys` documentation, there is nothing that gives that bit of information. Maybe someone has some ideas.

2020-09-20 11:34 UTC, Akuli commented
I think we could always load both history files if they exist.

2020-09-24 23:56 UTC, adder46 commented
I think we should just drop the goal of supporting IPython and keep `pyhstr` as an extension for the standard shell only. What do you think?

2020-09-25 12:42 UTC, mcataford commented
Sorry, it's been a pretty hectic week so I couldn't come back to it just yet. I've got a way forward on having the iPython history be fed in if it exists, I'll push up those changes later tonight!

On September 24, 2020 7:56:19 p.m. EDT, adder46 <notifications@github.com> wrote:
>I think we should just drop the goal of supporting IPython and keep
>`pyhstr` as an extension for the standard shell only. What do you
>think?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/adder46/pyhstr/pull/1#issuecomment-698645845

2020-09-27 20:17 UTC, adder46 commented
I don't think just trying to import IPython and having that be an indicator of whether or not you're actually running IPython is going to work.

2020-09-29 20:35 UTC, adder46 commented
I did a bit of exploring, and you can tell whether the user is in the IPython shell with `get_ipython` which returns `None` otherwise. Then a bit unusual thing is that it stores history in an sqlite file. So we'd need to choose whether we want to read that file into a list or something, or use [this](https://github.com/ipython/ipython/blob/master/IPython/core/magics/history.py#L99) somehow.

2020-09-29 22:50 UTC, adder46 commented
I'm closing this, the fixes are [here](https://github.com/adder46/pyhstr/pull/5).

2020-09-29 22:50 UTC, closed without merging