Fix regex issue
adder46/pyhstr pull request #3
Opened 2020-09-20 20:25 UTC by adder46

This PR should fix the regex bug(s) that we have overlooked.

2020-09-20 20:31 UTC, Akuli requested changes
Haven't tried the code yet, just pointing out things I saw by reading it

What happens if you enter a bad regex and then scroll? Does it crash?

2020-09-20 20:31 UTC, Akuli commented on pyhstr/user_interface.py
> +        prompt = f"Invalid regex. Try again."
`f` not needed

2020-09-20 20:31 UTC, Akuli commented on pyhstr/user_interface.py
> +                        m.span() for m in re.finditer(self._re_compile(self.search_string), entry)
small cleanup:

```suggestion
                        m.span() for m in self._re_compile(self.search_string).finditer(entry)
```

2020-09-20 20:31 UTC, Akuli commented on pyhstr/user_interface.py
> +    def _re_compile(self, search_string):
Several things:
- Why does the function name start with `_`?
- How about a more descriptive function name, such as `create_search_string_regex`?
- This function is always called so that `search_string == self.search_string`. Just use `self.search_string` instead and get rid of the `search_string` argument.

2020-09-20 21:54 UTC, adder46 commented on pyhstr/user_interface.py
> +        prompt = f"Invalid regex. Try again."
Might be needed, because I'll try to show the invalid regex.

2020-09-20 21:58 UTC, adder46 commented on pyhstr/user_interface.py
> +    def _re_compile(self, search_string):
As for the first bullet point, I thought it should start with an underscore because it's a private thing internal to the program. But, I agree with the second bullet point and I'll change the name. Third bullet point: agreed.

2020-09-20 22:02 UTC, adder46 commented
> Haven't tried the code yet, just pointing out things I saw by reading it
> 
> What happens if you enter a bad regex and then scroll? Does it crash?

Yeah, it crashes. Needs addressing.

2020-09-20 22:08 UTC, Akuli commented
Code looks good to me now, but I'm not happy with how it behaves.

Let's say I want to type a regex like `(prin|inpu)t`. When I type the first `(`, it shows the error and doesn't let me continue typing. I think the error should appear but let me finish typing the regex, so that eventually, the regex will be correct and filtering will work

2020-09-20 22:14 UTC, adder46 commented
> Code looks good to me now, but I'm not happy with how it behaves.
> 
> Let's say I want to type a regex like `(prin|inpu)t`. When I type the first `(`, it shows the error and doesn't let me continue typing. I think the error should appear but let me finish typing the regex, so that eventually, the regex will be correct and filtering will work

I think it does actually let you continue typing, it's that what you type isn't being printed to screen until you type in something correct. For instance, try switching to regex mode and type `print()`.

2020-09-20 22:15 UTC, Akuli commented
That behaviour isn't great IMO. I would never have guessed that :D

2020-09-20 22:16 UTC, adder46 commented
I agree, I'll have to figure this out, too.

2020-09-20 22:22 UTC, Akuli requested changes

2020-09-20 22:22 UTC, Akuli commented on pyhstr/application.py
> +                if self.user_interface.create_search_string_regex().search(self.user_interface.search_string)
I was wondering why it didn't seem to filter anything. Here's why.

```suggestion
                if self.user_interface.create_search_string_regex().search(cmd)
```

2020-09-21 00:33 UTC, adder46 commented
So, now you can see what you type. IMO, now the issues are the following:

- The screen should be cleared when invalid regex is input.
- Scrolling when in invalid regex is input breaks the program.

2020-09-21 09:16 UTC, Akuli reviewed
The code looks pretty good! I still have a couple small things.

2020-09-21 09:16 UTC, Akuli commented on pyhstr/application.py
> +            app.all_entries = app.to_restore.copy()
What does this do?

2020-09-21 09:16 UTC, Akuli commented on pyhstr/user_interface.py
> +            return re.compile('')
You could use a regex that matches nothing, similar to this:

https://github.com/Akuli/porcupine/blob/7d3f13546d375cccba73525e3b3f6240b8e74b23/porcupine/plugins/filetypes.py#L71

That works because there can't be any text before `^`, the start of a string.

2020-09-21 10:12 UTC, adder46 commented on pyhstr/application.py
> +            app.all_entries = app.to_restore.copy()
It restores the history because we clear it on line 140 in order to get rid of "zombie" entries when invalid regex is input.

2020-09-21 17:25 UTC, Akuli approved these changes

2020-09-21 17:28 UTC, merged